name: swiggy_clone
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  diamond_bottom_bar: ^1.0.0
  flutter:
    sdk: flutter
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  google_fonts: ^4.0.4
  http: ^0.13.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/

